### ISSUE TITLE
Issue||"Return to shop" item page||"View Cart" on hover text disappears

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#100]
Go to "Return to shop" page. 
Select a course to add course to the cart. 
Once the course is added a "View Cart" option will be available. 
When user hovers over "View Cart" option, the text "View Cart" disappears. 

PFA to the screenshot attached -
https://screenrec.com/share/YFMKn73q0L

**Comment by Pankaj-Dhote31** [comment]
Issue solved

**Comment by Tejashri-23** [comment]
Closed. 
https://screenrec.com/share/N2oZhJnsqH
