### ISSUE TITLE
Functional issue||Review||Star Rating shows one extra rating than chosen

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#101]
Go to website > click on one of the courses > select take this course. 
Add a review and select star ratings 
Click on "SUBMIT". 

The rating increases by one. 

PFA to the screenshot video attached -
https://screenrec.com/share/yZrkDxTwGu

**Comment by sachinkanase10** [comment]
Issue solved ,please check

**Comment by Tejashri-23** [comment]
Closed
