### ISSUE TITLE
Functional issue||Email-id||No validation on edit profile 

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#102]
Go to My Profile>Edit>edit email-id without the required format>click on "Save Changes" 

PFA to the screenshot attached :-
https://screenrec.com/share/RLpymNPoQO

**Comment by Pankaj-Dhote31** [comment]
Email id field is repeated in the form. so removed From the Form

**Comment by Tejashri-23** [comment]
closed.
