### ISSUE TITLE
Issue||Add to Cart Button||On Hover||Change in colour

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#103]
The "Add to Cart" button changes to purple font colour when user hovers over the cart option. Please change the font colour to a lighter shade. 

PFA to the screenshot attached -
https://screenrec.com/share/xXSCQm4yr3

**Comment by Pankaj-Dhote31** [comment]
Their is no need to change the color because it already looks good & text is readable format.

**Comment by Tejashri-23** [comment]
As per discussion , closed this issue.
