### ISSUE TITLE
Functional issue||Password validation||Not applied

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#105]
As of now , no specific validations applied to password. 

PFA to the screenshot attached :-
https://screenrec.com/share/8sWxlR76Ie

**Comment by sachinkanase10** [comment]
Password validation of 8 character is applied, please check

**Comment by Tejashri-23** [comment]
For more secure password combination , a password value of the following format to be applied :- 
Password length of 8 charachters : Done and verified
One special charachter 
One numeric and one alphabetic charachter

**Comment by Tejashri-23** [comment]
As per discussion, password length can be applied.
