### ISSUE TITLE
Suggestion/Issue||Functional||Necessary validation for contactus form

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#11]
As of now, the alert is not focused for name,email and no user can submit contact form 
without any query.

Expected result :-  
Alert to be focussed w.r.t to the field and validation to be applied for query form. 

PFA to the screenshot attached 
https://www.screencast.com/t/pCgZbHd7

**Comment by Gautam-destek** [comment]
resolved

**Comment by Tejashri-23** [comment]
closed
