### ISSUE TITLE
Functional issue||Dashboard||Course count  not getting updated

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#113]
Login to the website > go to profile.
Go to Dashboard section > the course widget count does not show the actual count of courses in course section.

PFA to the screenshot attached -
https://www.screencast.com/t/H6flEGCv1

**Comment by sachinkanase10** [comment]
This is a course count for finished courses

**Comment by sandeepwagh90** [comment]
Means as per above when students will finish the course, then count will get updated.
