### ISSUE TITLE
Functional issue || Add to cart Pop-up || Cross (x) button not working

### ISSUE THREAD

**Issue by sandeepwagh90** [Tejashri-23/LMS#117]
URL-https://screenrec.com/share/3ne70bE8cd
URL screenshot-
https://screenrec.com/share/9W1OKht27a
Scenarion- Add court in the cart and try to close the card pop-up by using cross button

**Comment by Tejashri-23** [comment]
PFA to the screenshot attached -
https://www.screencast.com/t/XIswvfeMDU
"x" button not working for "Add to Cart" prodcut widget.

**Comment by sachinkanase10** [comment]
It's in built class has event binded ,which cannot handle from an external script

**Comment by sandeepwagh90** [comment]
As mention above developers comment closing the issue
