### ISSUE TITLE
Functional issue || Student profile || Activity || Personal || Add file and Post Updates || Favorite ||  Onclick of "Remove Favorite" the post should be removed.

### ISSUE THREAD

**Issue by sandeepwagh90** [Tejashri-23/LMS#119]
Video-https://screenrec.com/share/4bHvknmIRs
Scenario- When student post any update and make it as a favorite, then user remove favorite from favorite tab, The post should removed from the favorite tab

**Comment by sachinkanase10** [comment]
This issue is discuss with Tejashree, as it's inbuilt functionality of crm ,we cannot manage that, when you reload that page it will be not there

**Comment by sandeepwagh90** [comment]
Ok,As per above comment and discussion we are closing the issue
