### ISSUE TITLE
Design issue||Faculty||glitches when user onclicks on "Courses by instructor"

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#14]
Text overlap and design mismatch.

Steps of execution -
Go to Faculty > click on one of the instructors who does not own any courses. 

PFA to the screenshot attached :
https://screenrec.com/share/M5Ghnvm9B6

**Comment by Gautam-destek** [comment]
resolved

**Comment by Tejashri-23** [comment]
closed
