### ISSUE TITLE
Design issue || Browser specific || Mozilla firefox

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#2]
Design mismatch alignment of header and logo with the increase in resolution. 

PFA to the screenshot attached for reference :-
https://screenrec.com/share/bIn9xdqZP0

**Comment by Pankaj-Dhote31** [comment]
Screen resolution wise alignment is different so this is not a bug. in my system it look better

**Comment by Tejashri-23** [comment]
Closed.
