### ISSUE TITLE
Design issue||Profile Page||Empty Spacing between sections

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#20]
Unnecessary spacing between sections post login.
PFA to the screenshot attached :-
https://www.screencast.com/t/5ivMcIWe8xe

**Comment by Pankaj-Dhote31** [comment]
Background image change make it light dark. issue solved

**Comment by Tejashri-23** [comment]
Extra space handled with the background image. 
https://www.screencast.com/t/JpERuIihbQch
Closed
