### ISSUE TITLE
Functional issue||My Profile>Activity||Remove favourite

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#23]
Steps of execution -
Login to the website.
Go to My Profile > Activities.
Add activity to favourites section and then go to Favourites.
Click on "Remove favourite" to remove the activity added to favourite section.

Actual result -
The item remains in the favourite section even after removal. There is no concurrent or dynamic reflection of the activity status.

PFA to the screenshot attached -
https://screenrec.com/share/dyzPGtU4SW

**Comment by sachinkanase10** [comment]
Please check this issue again, I follow all steps mention above by you and I am able to make it favourite and then remove it from favourites successfully.

**Comment by Tejashri-23** [comment]
Please refer to the video attached for reference :-
https://screenrec.com/share/4b8VZjw6Gc

**Comment by Tejashri-23** [comment]
As per discussion, issue closed.
