### ISSUE TITLE
Design issue||MyProfile>Activity>Personal||File pop-up menu

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#24]
Steps of Execution -
Login using valid credentials.
Go to My Profile>Activity>Personal

Upload file pop-up menu at Activities>My Profile should have only button or text link to select file.
https://www.screencast.com/t/HZ5lwoQg

**Comment by Gautam-destek** [comment]
resolved

**Comment by Tejashri-23** [comment]
closed
https://www.screencast.com/t/eFIX5LuYUW3

**Comment by Tejashri-23** [comment]
Please check the alignment , it was resolved , reappeared now
https://www.screencast.com/t/eFIX5LuYUW3
