### ISSUE TITLE
Design issue||My Profile>activity||Favourites

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#25]
Login using valid credentials.
Go to My Profile>Activities>Personal section.
Click on Add File option.

PFA to the screenshot attached -
https://www.screencast.com/t/dXNWYOao1

**Comment by sachinkanase10** [comment]
Changes done, please check

**Comment by Tejashri-23** [comment]
Closed. 
https://www.screencast.com/t/bbPyYMIXNJ0
