### ISSUE TITLE
Functional Issue||Fileupload pop-up||My Profile

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#26]
Actual result -
The pop-up for file upload closes when user clicks on the background area. 

Expected result -
The pop-up for file upload should disappear when user clicks on "x" option. 

PFA to the screenshot attached for reference -
https://screenrec.com/share/7OfCJNnXyb

**Comment by sachinkanase10** [comment]
There is inbuilt event binding, which we cannot alter from external js

**Comment by sandeepwagh90** [comment]
Ok,As above comment we are closing issue
