### ISSUE TITLE
Functional issue||Profile||Load More option displays duplicate data

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#28]
Go to My Profile > Activity > Load More option
Click on "Load More" option multiple times. 

Actual result -
The previous data gets loaded as many times as the user clicks on "Load More" option.

PFA to the screenshot attached :-
https://screenrec.com/share/ThUgBpsRCE

**Comment by Pankaj-Dhote31** [comment]
This is not a bug. if user had a proper internet speed then it works fine. in low internet connect user click on it the script get more time to load.

**Comment by Tejashri-23** [comment]
Okay, closed as shows appropriate data for a single click.
As per discussion with @Shubham983 and @Pankaj-Dhote31 , closed issue
