### ISSUE TITLE
Design issue||Failed to log in page||Logo overlapped by background.

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#31]
The logo text on the login page gets hidden by the background when the user clicks and fails to login.

PFA to the screenshot attached -
https://www.screencast.com/t/RYWKLDRtQ

**Comment by Gautam-destek** [comment]
resolved

**Comment by Tejashri-23** [comment]
Please make the background a little lighter and the text in white bold. 
https://www.screencast.com/t/KLW9b9DLyqR4

**Comment by Tejashri-23** [comment]
As per discussion, closed
