### ISSUE TITLE
Design issue||Failed to login page||Text i/p font size not consistent

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#32]
Text i/p font size is not consistent for the login pop-up and failed to login page.

PFA to the screenshot attached -
https://www.screencast.com/t/feDSXXZ9ucGk

**Comment by Pankaj-Dhote31** [comment]
login popup & failed to login page design is different to manage design proper we need to increase the font size in failed to login page, if we keep it same then it not look good

**Comment by Tejashri-23** [comment]
Okay : noted 
we can adjust the text font size to 16px.

**Comment by Tejashri-23** [comment]
As per discussion, closed
