### ISSUE TITLE
Issue||Activation-email||Activate button missing

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#33]
The content "click on activate button" shows a hyperlink instead of the button to activate the account.

Expected result suggested -
1. The links for activation to be replaced by a button : "Activate your account". 
2. Change the text content.

PFA to the screenshot attached -
https://www.screencast.com/t/WgeR70pHqK

**Comment by Pankaj-Dhote31** [comment]
This is not a bug. please check activation mail once again.

**Comment by Tejashri-23** [comment]
It is an enhancement not a bug.

**Comment by Tejashri-23** [comment]
As per the discussion with the development team, it is predefined template hence closed.
