### ISSUE TITLE
Issue||Forgot password page||Text i/p and textbox size not consistent

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#34]
Steps of execution -
1. Go to website and click on Login.
2. Click on Login button again.
3. Click on Click on "Forgot password" page. 

The textbox size and text i/p value font size and dimensions should be the same and consistent. 

PFA to the screenshot attached for reference -
https://www.screencast.com/t/mVUgEdix4SDF

**Comment by Pankaj-Dhote31** [comment]
as per page design we keep the font size. so this is not a bug

**Comment by Tejashri-23** [comment]
Keep the textbox i/p font size as 16px with the icon position relative to the textbox. 
Refer to the screenshot attached - 
https://www.screencast.com/t/nshdYUVq

**Comment by Tejashri-23** [comment]
As per discussion , closed
