### ISSUE TITLE
Feedback recommendation||Kohinoor script

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#40]
Kohinoor font style to be used to show the content on the page. 

Need to discuss with @Pankaj-Dhote31 to implement further.

**Comment by Pankaj-Dhote31** [comment]
font applied on demo link if client get approval then we change the font in current site

**Comment by Tejashri-23** [comment]
As discussed, reviewed font on the demo website, so if approved, then shall reopen again.
