### ISSUE TITLE
Feedback recommendation||Add a tab section

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#41]
Add a tab section within Training > Courses > Select course > Add a tab section named Course Outcome in the following order -
Home-Curriculum-Course Outcome

As per discussion with content team, the course outcome content is given on the shared drive. 

PFA to the screenshot attached -
https://www.screencast.com/t/RT0Y3HGb1O

**Comment by Pankaj-Dhote31** [comment]
This section added under Home Section

**Comment by Tejashri-23** [comment]
closed
