### ISSUE TITLE
Feedback recommendation|| USB key points to be added on the banner

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#43]
USBkey points to be reworded in a proper manner to look more original and meaningful without loosing the basic essence with rephrasing.
(keywords : shared with the content writer and updated with the changes on the shared drive)

https://www.screencast.com/t/x5OiJWqtrTz

**Comment by Gautam-destek** [comment]
Done (resolved)

**Comment by Tejashri-23** [comment]
Done.
