### ISSUE TITLE
Feedback recommendation||Banner images more relative of the idea

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#44]
1. Consider the e-learning and recent pictures for the image at the banner in relation.
2. Logo at the center in a scrolling manner and then grey picture showing the graduation picture.
screenshot attached for reference -
https://www.screencast.com/t/HvxQHF2OgS

**Comment by Pankaj-Dhote31** [comment]
E-learning image updated in banner & logo center is not possible

**Comment by Tejashri-23** [comment]
e-learning image updated and done.
