### ISSUE TITLE
Feedback || Captivating content for each of the picture on infrastructure page

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#47]
PFA to the screenshot attached -
https://www.screencast.com/t/f364eHkA7Dw

**Comment by Gautam-destek** [comment]
Captivating content not available

**Comment by Tejashri-23** [comment]
Yes, it is an enhancement, so needs to be there until it is worked upon or not specified by the client.

**Comment by Tejashri-23** [comment]
Client specifications for infrastructure page to be confirmed, reported to Shubham.

**Comment by Tejashri-23** [comment]
As per discussion, closed
