### ISSUE TITLE
Suggestion || Email content change for activation link

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#48]
Certain changes to be done to email body as mentioned below -

Thank you for registering with us!
You are just few clicks away from activation of your account.
Follow the steps and you will be done in no time.
1. Click on the link given below: (href link)
2. Click on the Activate button. 
If the Activate button key is inactive ,
kindly copy paste the following text into the field provided and your account will be activated.
(key)
If you are still facing difficulties, please reach our support team at: support team id
Happy learning to you!
Regards,

PFA to the screenshot attached -
https://www.screencast.com/t/WgeR70pHqK

**Comment by Gautam-destek** [comment]
![ac_active](https://user-images.githubusercontent.com/66715306/84563333-57dcf280-ad78-11ea-87d6-07827728e8d1.png)

**Comment by Gautam-destek** [comment]
email format not changeable

**Comment by Tejashri-23** [comment]
PFA to the screenshot attached for reference in the comment section above.

**Comment by Tejashri-23** [comment]
As per discussion with the development team, sometimes the user forgets to have a look at the 
link attached below , hence closed
