### ISSUE TITLE
Issue||RSS feed icon navigating to HTML code content

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#49]
@Pankaj-Dhote31 : do we have feeds section to be added in addition to the other sources like
fb,twitter and dribble.
Please remove the icon if we are not going to keep a feed section.

PFA to the screenshot video for reference -
https://screenrec.com/share/SV5DqOgir3

**Comment by Pankaj-Dhote31** [comment]
Icon removed

**Comment by Tejashri-23** [comment]
closed
