### ISSUE TITLE
Design Issue || Footer || Logo text overlapped with background

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#5]
Logo content is overlapped with the background at the footer. 

Logo should be clearly visible with the text inline without hindrance to the background theme chosen.

PFA to the screenshot attached 
[https://www.screencast.com/t/wDHwR79g](url)

**Comment by Gautam-destek** [comment]
resolved

**Comment by Tejashri-23** [comment]
closed
