### ISSUE TITLE
Issue||Login page||Lost Password page

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#50]
The lost password link to forgot password has multiple reference points. There should be only point of access to forgot password.

https://www.screencast.com/t/0nAOHLxE

**Comment by Gautam-destek** [comment]
it's working fine

**Comment by Tejashri-23** [comment]
Yes the functionality is working fine, but the only thing was to give the link to "forgot password" either
at the top or at the bottom.  PFA to the screenshot attached.

**Comment by Tejashri-23** [comment]
As per discussion, closed
