### ISSUE TITLE
Issue||Instructor profile||On Hover cursor disappears

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#51]
Login with valid credentials as a instructor.
Go to My Profile > courses > members > hover over page count.

The cursor disappears and an insert text cursor icon appears. 

PFA to the screenshot attached -
https://screenrec.com/share/wUTpqz6Fku

**Comment by Pankaj-Dhote31** [comment]
Issue Solved

**Comment by Tejashri-23** [comment]
closed
