### ISSUE TITLE
Functional issue||Load More option||Load More option

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#52]
Load More option displays duplicate results as many times as the user clicks on the load more button.

PFA to the screenshot attached -
https://screenrec.com/share/bMVfSZDQyu

**Comment by Pankaj-Dhote31** [comment]
This is not a bug. if user had a proper internet speed then it works fine. in low internet connect user click on it the script get more time to load.

**Comment by Tejashri-23** [comment]
in sync with the other load more issue, closed this
