### ISSUE TITLE
Design issue||reply textbox||Font colour to be replaced

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#57]
PFA to the screenshot video attached -
https://www.screencast.com/t/j4aO2v0Z8c3

**Comment by Pankaj-Dhote31** [comment]
Issue solved.

**Comment by Tejashri-23** [comment]
still shows the same font colour when user uses reply feature in notification section.
Please check - 
https://screenrec.com/share/owaHBGyzMl

**Comment by Tejashri-23** [comment]
as per discussion,  this is time consuming and will take time.

**Comment by Pankaj-Dhote31** [comment]
color changed. issue solved

**Comment by Tejashri-23** [comment]
Closed 
https://www.screencast.com/t/wqgbsxUSRan
