### ISSUE TITLE
Functional issue || Activities section>Notification || Profile

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#58]
1. Login as a student and and an instructor on two different profiles.
2. Click on respective profiles and go to dashboard section.
3. Go to Dashboard>My Activity section>send multiple replies to a student's comment.
4. Now go to Student login and check for the count updation.

Actual result -
Notification count gets updated when user clicks on Notification section. 

Expected result - 
Notification count should be updated dynamically before user clicks on Notification section.

PFA to the screenshot attached for reference -
https://screenrec.com/share/LqN9UJDv7c

**Comment by Gautam-destek** [comment]
as per discussion solved

**Comment by Tejashri-23** [comment]
As per discussion , count gets updated on refresh option.
