### ISSUE TITLE
Design issue || Banner on Home Page || Discover more button not clickable

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#6]
"Discover more" button not clickable as button is a clickable event.

PFA to the screenshot attached 
https://screenrec.com/share/BLJKRe8sM4

**Comment by Pankaj-Dhote31** [comment]
Issue Solved

**Comment by Tejashri-23** [comment]
page is redirected to About Us Page.
@Shubham983 - do we have to design a page.
