### ISSUE TITLE
Functional issue||Buddy drive||Cancel option also saves the file.

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#64]
Login through instructor credentials.
Go to My profile>courses>drive.
Click on the icon to insert file on drive.
Add necessary details and click on the "Cancel" option.

The file gets saved when user clicks on "Cancel button".

PFA to the screenshot attached -
https://screenrec.com/share/tmMgjA4fhr

**Comment by Gautam-destek** [comment]
cancel button working properly. its not issue

**Comment by Tejashri-23** [comment]
closed
