### ISSUE TITLE
Design issue||Courses||Admin section

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#65]
PFA to the screenshot attached -
https://www.screencast.com/t/9JlRYS3Y7p

**Comment by Pankaj-Dhote31** [comment]
In my system it look proper. i think your page was not properly loaded please refresh the page

**Comment by Tejashri-23** [comment]
I have refreshed and loaded the page, but the design issue still remains. 
https://screenrec.com/share/UYOmNDEQvP

**Comment by Gautam-destek** [comment]
resolved

**Comment by Gautam-destek** [comment]
![stats](https://user-images.githubusercontent.com/66715306/85132665-df35d480-b256-11ea-9a15-3f92d70dfe21.png)

**Comment by Tejashri-23** [comment]
As per discussion, closed  as not reproducible and occurred on my tester's side.
