### ISSUE TITLE
Design issue||Browser specific||header and footer design

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#69]
The logo image and the footer bottom is not aligned on IE. 
Checked on version 11. 

PFA to the screenshot video attached -
https://screenrec.com/share/tYK2iyLHqf

**Comment by Pankaj-Dhote31** [comment]
This problem is only with internet explorer browser. so it can not solved

**Comment by Gautam-destek** [comment]
default theme alternate stylesheet not available for microsoft internet explorer. so it can not solved

**Comment by Tejashri-23** [comment]
As per discussion with the team , closed
