### ISSUE TITLE
Functional issue||Edit profile||Email-id

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#72]
1. Login to the website.
2. Go to Profile > Edit profile.
3. Scroll down to see the email-id textbox. 

PFA to the screenshot attached -
https://www.screencast.com/t/avJjLY4sZwJt

As of now, email-id is not pre-filled as the id was used during registration.

Expected result -
The email-id used during login for existing users should be auto-filled in the email-id textbox.

**Comment by Pankaj-Dhote31** [comment]
You are login with old user registration form. so you need to enter email id then next time it will be autofilled.

**Comment by Tejashri-23** [comment]
Current flow -
Works for new registration , shows auto-filled email-id and for existing user post edit and save , the functionality works. 
Expected outcome -
For old users, email-id should be auto filled with the address that the user had used at the time of login.

**Comment by Pankaj-Dhote31** [comment]
issue closed

**Comment by Tejashri-23** [comment]
closed
