### ISSUE TITLE
Functional issue||Registration page||Contact number validation

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#74]
As of now, contact number and whatsapp number accepts 'n' number of digits.

Expected result -
1. Apply limit to not accept more than 10 digits for mobile number. 
2. To restrict while typing the digits in the textbox.

PFA to the screenshot attached -
https://www.screencast.com/t/yd8ovpfy

**Comment by Gautam-destek** [comment]
resolved

**Comment by Tejashri-23** [comment]
closed
