### ISSUE TITLE
Suggestion||Profile heading title to be changed

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#75]
Profile heading title to be changed : "Base" to "My Profile" on view profile and edit profile option.

PFA to the screenshot attached -
https://www.screencast.com/t/nNREc7zvDu

**Comment by Pankaj-Dhote31** [comment]
Issue Solved

**Comment by Tejashri-23** [comment]
closed but improvisation required 
https://www.screencast.com/t/XidM0SO8q4

**Comment by Tejashri-23** [comment]
as per discussion , closed
