### ISSUE TITLE
Functional issue||Registration form||Update information

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#76]
Profile updation not taking place for existing user when user updates the social links for fb and twitter.
Getting error  - 
**THERE WAS A PROBLEM UPDATING SOME OF YOUR PROFILE INFORMATION. PLEASE TRY AGAIN.**

PFA to the screenshot attached :-  
https://www.screencast.com/t/OftP8AzkR

**Comment by Pankaj-Dhote31** [comment]
Issue Solved. First fill all base filed then update social field

**Comment by Tejashri-23** [comment]
closed.
