### ISSUE TITLE
Issue||My Profile||Social profile

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#77]
There are two social profile buttons in My Profile > edit. 
One of the social media section to be removed to have only one point of social link updation. 
PFA to the screenshot
https://www.screencast.com/t/cdvqpn6qRo

**Comment by Pankaj-Dhote31** [comment]
Issue solved. removed duplicate social profiles

**Comment by Tejashri-23** [comment]
closed
