### ISSUE TITLE
Suggestion||Social profile||Duplicate headings

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#78]
Two headings of Social Profile shown on view profile. 

PFA to the screenshot attached -
https://www.screencast.com/t/ulmTC7iYRYT

**Comment by Pankaj-Dhote31** [comment]
Issue solved

**Comment by Tejashri-23** [comment]
Reopened.
https://screenrec.com/share/6fpWvuJmUb

**Comment by Pankaj-Dhote31** [comment]
check once again. with different student id

**Comment by Tejashri-23** [comment]
checked with my profile-id , closed
https://www.screencast.com/t/6Bi3IISVNX
