### ISSUE TITLE
Issue||Registration form||Icons for buttons missing on register form

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#79]
PFA to the screenshot attached for reference :-
https://www.screencast.com/t/8tw97IXZdwe

**Comment by Pankaj-Dhote31** [comment]
issue solved

**Comment by Tejashri-23** [comment]
Yes, issue is solved partially. Please remove the button placed at the bottom also.
https://www.screencast.com/t/JZj2SufCl

**Comment by Pankaj-Dhote31** [comment]
issue solved

**Comment by Tejashri-23** [comment]
issue closed.
https://www.screencast.com/t/IlZqjo4g
