### ISSUE TITLE
Issue||Consultancy Request form||Phone number validation

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#82]
Phone number validation not applied. 
We should restrict the user by allowing only to accept digits 0-9 and restrict the entry of the total length accepted. 

PFA to the screenshots attached :-
https://www.screencast.com/t/Nb6HOD6aw
https://screenrec.com/share/KHnxsRMhiv

**Comment by sachinkanase10** [comment]
Issue resolved , please check

**Comment by Tejashri-23** [comment]
issue closed. 
https://screenrec.com/share/rIuCEPevMj
