### ISSUE TITLE
Issue||Consultancy request form||multiple font colour

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#85]
Please keep one generic font colour for all the fields on the request form. 

PFA to the screenshot attached -
https://www.screencast.com/t/rSZufO71Us

**Comment by Pankaj-Dhote31** [comment]
Issue Solved

**Comment by Tejashri-23** [comment]
issue closed.
https://www.screencast.com/t/OtbJojsAx
