### ISSUE TITLE
Issue||Quick Links||Login and Contact redirects to wrong links

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#86]
Login pop-up and contact form should redirect to login and contact us page respectively. 

PFA to the screenshot attached for reference -
https://screenrec.com/share/IHSNxvUdG1

**Comment by Pankaj-Dhote31** [comment]
Issue Solved

**Comment by Tejashri-23** [comment]
issue closed.
https://screenrec.com/share/ojkX96MUhn
