### ISSUE TITLE
Suggestion||Enquiry form||"Your message" not a required field. 

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#87]
As of now, Enquiry can be sent without any message. 

Expected result -
Apply validation as a required field for "Your Message" field. 

PFA to the screenshot attached for reference :-
https://www.screencast.com/t/gbEy5QimXXad

**Comment by Pankaj-Dhote31** [comment]
Issue Solved

**Comment by Tejashri-23** [comment]
Required field added for "Your Message" but enquiry form gets submitted with empty message.

**Comment by Pankaj-Dhote31** [comment]
Issue Solved.

**Comment by Tejashri-23** [comment]
Issue reopened as "your message" fields gets submitted even when user has not added any message. 
PFA to the screenshot attached -
https://screenrec.com/share/NuDwjLhgUX

**Comment by Pankaj-Dhote31** [comment]
i was checking the contact from. now i solved this error

**Comment by Tejashri-23** [comment]
Issue closed
