### ISSUE TITLE
Design issue || Footer section || Facebook icon not shown

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#9]
Facebook icon not visible on homepage. Shows paceholder instead of showing the facebook icon on the following pages :-
Home 
About Us
Contact us

PFA to the screenshot attached 
https://www.screencast.com/t/UeukseMrT

**Comment by Gautam-destek** [comment]
resolved

**Comment by Tejashri-23** [comment]
closed
