### ISSUE TITLE
Functional issue||Contact us form||Not getting saved

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#92]
Contact us form is not getting saved when user enters details and clicks on "Send" button. 

PFA to the screenshot attached :-
https://screenrec.com/share/TMWo5LSm9g

**Comment by Pankaj-Dhote31** [comment]
There is not issue. please check your internet connection. please check once again. issue solved

**Comment by Tejashri-23** [comment]
Yes, contact form getting saved.
