### ISSUE TITLE
Design issue||Home Page||Course info 

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#97]
Go to HomePage > Scroll down to trainings section > click on course info > take this course

The star icons for review shows placeholder for icons. 

PFA to the screenshot attached for reference -
https://www.screencast.com/t/XIo3HB1qEuGJ

**Comment by Pankaj-Dhote31** [comment]
In Heading bredcum Heading is always visible because we add couse as a prduct. in template add to cart functionality is under product section. & image issue solved

**Comment by Tejashri-23** [comment]
issue closed. 
https://www.screencast.com/t/xQexYVrO
