### ISSUE TITLE
Suggestion/Issue||"Subscribe to"||change in error message

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#98]
Change in alert message for the "Subscribe to" option. 

PFA to the screenshot attached for reference -
https://www.screencast.com/t/hvSs3cDwH2

**Comment by Pankaj-Dhote31** [comment]
This is wordpress default error message. it  is also a correct message

**Comment by Tejashri-23** [comment]
As per discussion,closed this issue.
