### ISSUE TITLE
Functional issue||"Return to Shop" Page||Add items to cart dynamic count updation

### ISSUE THREAD

**Issue by Tejashri-23** [Tejashri-23/LMS#99]
When user add a course from the "return to shop" page, the course gets added to the cart but the count does not get updated dynamically but when user refresh the page. 

Expected result :- 
1. Dynamically update the count. 
2. Show "Added to Cart" option for the course that is already added to the cart. 

PFA to the screenshot attached. 
screenshot : https://www.screencast.com/t/vrPyTcv4v
video : https://screenrec.com/share/2hweHJF79c

**Comment by Pankaj-Dhote31** [comment]
It is a wordpress  default  cart functionality

**Comment by Tejashri-23** [comment]
Issue is solved by handling two cases - 
1.  Cart gets updated when user adds a course to the cart. 
2. User cannot add the same course again to the cart. 

The count will get updated on page refresh as it is default wordpress functionality. 
https://screenrec.com/share/yZrkDxTwGu
